enableRobotsTXT: true 
baseURL: http://pengelly.netlify.app/
languageCode: en-us
title: Cass Mess
params: 
 navlinks:
    - home: yes
      name: Home
      url: /
    - name: Portfolio
      url: portfolio/
    - name: Posts
      url: posts/
 social:
      github: https://github.com/cass-code
      linkedin: https://www.instagram.com/cass.mess/
      instagram: https://www.instagram.com/cass.mess/

   

