enableRobotsTXT = true 
baseURL = 'http://pengelly.netlify.app/'
languageCode = 'en-us'
title = 'Cass Mess'
params:
  description: Art portfolio
  social:
    github: https://github.com/cass-code
    instagram: https://www.instagram.com/cass.mess/
    linkedin: https://www.linkedin.com/in/cassandra-pengelly/
  style: default